const FormData = [{
  'CNameCN': '按钮',
  'CNameEN': 'button',
  'parent': 'form',
  'type': 'button',
  'component': 'CButton',
  'config': {
    'ControlID': 'b1a95fd3-7019-467c-8dbe-258bc56d17b4',
    'CBelong': 'form',
    'CTitleCN': '按钮',
    'CTitleEN': 'button',
    'CName': 'CButton',
    'layoutModel': 'percentLayout',
    'currentLayout': {'name': '百分比', 'default': '25', 'value': 'percentLayout', 'status': true, 'max': 100},
    'methodDB': [{
      'id': 'fbc2b34f340a4632bf070c7c69fdd3b1',
      'edmmType': 'a3c01a6383ce4bb79c4d603b96c71831',
      'isCover': 0,
      'edmmName': 'orde_save',
      'edmmDesc': 'http://localhost:11101/orde/save',
      'edmmProgramType': '1',
      'edmmProgramStorage': null,
      'edmmTriggerCond': '',
      'edmmVer': '',
      'edmmDevelopDept': '',
      'edmmProgrammer': '',
      'edmmSeq': 1,
      'edmmStatus': '1',
      'edmmUpdateDesc': '',
      'isPlatformProgram': 0,
      'isDefined': null,
      'isDel': 0,
      'addtime': 1508837845000,
      'adduser': null,
      'modtime': 1508837869000,
      'moduser': null,
      'acctid': null,
      'edmmArithmeticDesc': 'http://localhost:11101/orde/save',
      'edmmArithmeticStorage': '',
      'edmmArithmeticSourceName': '',
      'edmmRequestType': '1',
      'edmmMethodType': '0',
      'edmmExecRate': '0',
      'edmmStartTime': '00:00',
      'edmmEndTime': '12:00',
      'edmmTypeName': '单据类方法',
      'edmtName': null,
      'edmProgramTypeName': null,
      'edmEdmdStatusName': null,
      'edmcName': '监管设置单类',
      'edmcId': null,
      'edmEdmdInsertArgType': null,
      'edmEdmdInsertArgName': null,
      'edmInsertArgDesc': null,
      'edmEdmdReturnArgType': null,
      'edmEdmdReturnName': null,
      'edmReturnDesc': null,
      'addtimeStr': '2017-10-24 17:37:25',
      'modtimeStr': '2017-10-24 17:37:49',
      'edmdVersion': null,
      'edmdId': null,
      'edmdStatus': null,
      'edcmId': '57e5a91e4b4c41399d8fe429143866bd',
      'edmmProgramSourceName': '',
      'edmTriggerCondName': null,
      'edmTriggerCondNameDesc': null,
      'disabled': true,
      'controlId': '7bcf6fe9-230d-4f98-a6da-6354b3be5ee4'
    }, {
      'id': '5730bfbfef744ba0ac9df8a5db386cb6',
      'edmmType': 'a3c01a6383ce4bb79c4d603b96c71831',
      'isCover': 0,
      'edmmName': 'orde_create',
      'edmmDesc': '创建一个”单据类对象”草稿, 该方法由”单据定义类对象”调用',
      'edmmProgramType': '1',
      'edmmProgramStorage': null,
      'edmmTriggerCond': '',
      'edmmVer': '',
      'edmmDevelopDept': '',
      'edmmProgrammer': '',
      'edmmSeq': 2,
      'edmmStatus': '1',
      'edmmUpdateDesc': '',
      'isPlatformProgram': 0,
      'isDefined': null,
      'isDel': 0,
      'addtime': 1508837422000,
      'adduser': null,
      'modtime': 1508838926000,
      'moduser': null,
      'acctid': null,
      'edmmArithmeticDesc': 'http://form-client-driver/orde/create',
      'edmmArithmeticStorage': '',
      'edmmArithmeticSourceName': '',
      'edmmRequestType': '1',
      'edmmMethodType': '0',
      'edmmExecRate': '0',
      'edmmStartTime': '00:00',
      'edmmEndTime': '12:00',
      'edmmTypeName': '单据类方法',
      'edmtName': null,
      'edmProgramTypeName': null,
      'edmEdmdStatusName': null,
      'edmcName': '监管设置单类',
      'edmcId': null,
      'edmEdmdInsertArgType': null,
      'edmEdmdInsertArgName': null,
      'edmInsertArgDesc': null,
      'edmEdmdReturnArgType': null,
      'edmEdmdReturnName': null,
      'edmReturnDesc': null,
      'addtimeStr': '2017-10-24 17:30:22',
      'modtimeStr': '2017-10-24 17:55:26',
      'edmdVersion': null,
      'edmdId': null,
      'edmdStatus': null,
      'edcmId': 'cfa24e09ad6e4c95953c7386a2075ef0',
      'edmmProgramSourceName': '',
      'edmTriggerCondName': null,
      'edmTriggerCondNameDesc': null,
      'disabled': true,
      'controlId': 'b1a95fd3-7019-467c-8dbe-258bc56d17b4'
    }],
    'methodDBModel': 'orde_create',
    'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {'name': '百分比', 'default': '25', 'value': 'percentLayout', 'status': true, 'max': 100}, {
      'name': '像素',
      'default': 100,
      'value': 'pixelLayout',
      'status': false,
      'max': null
    }, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
    'CAttribute': {
      'type': [{'value': 'primary', 'name': '提交', 'default': 'primary'}, {'value': 'danger', 'name': '审批', 'default': 'danger'}, {
        'value': '',
        'name': '普通',
        'default': ''
      }, {'value': 'info', 'name': '详情', 'default': 'info'}],
      'typeModel': '',
      'size': [{'value': 'large', 'name': '大'}, {'value': '', 'name': '普通'}, {'value': 'small', 'name': '小'}, {'value': 'mini', 'name': '微型'}],
      'sizeModel': '',
      'description': '',
      'height': '',
      'vertical': ['top', 'middle', 'bottom']
    },
    'CKey': {'default': 'orde_create', 'type': '', 'keyMethods': ''},
    'Status': {'status': false, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': []},
    'Icon': {
      'status': false,
      'chooseStatus': false,
      'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
      'positionModel': '',
      'className': '',
      'content': '',
      'title': '',
      'library': ''
    },
    'ControlProperties': ''
  },
  'id': 'b1a95fd3-7019-467c-8dbe-258bc56d17b4'
}, {
  'CNameCN': '按钮',
  'CNameEN': 'button',
  'parent': 'form',
  'type': 'button',
  'component': 'CButton',
  'config': {
    'ControlID': '7bcf6fe9-230d-4f98-a6da-6354b3be5ee4',
    'CBelong': 'form',
    'CTitleCN': '提交按钮',
    'CTitleEN': 'button',
    'CName': 'CButton',
    'layoutModel': 'percentLayout',
    'currentLayout': {'name': '百分比', 'default': '50', 'value': 'percentLayout', 'status': true, 'max': 100},
    'methodDB': [{
      'id': 'fbc2b34f340a4632bf070c7c69fdd3b1',
      'edmmType': 'a3c01a6383ce4bb79c4d603b96c71831',
      'isCover': 0,
      'edmmName': 'orde_save',
      'edmmDesc': 'http://localhost:11101/orde/save',
      'edmmProgramType': '1',
      'edmmProgramStorage': null,
      'edmmTriggerCond': '',
      'edmmVer': '',
      'edmmDevelopDept': '',
      'edmmProgrammer': '',
      'edmmSeq': 1,
      'edmmStatus': '1',
      'edmmUpdateDesc': '',
      'isPlatformProgram': 0,
      'isDefined': null,
      'isDel': 0,
      'addtime': 1508837845000,
      'adduser': null,
      'modtime': 1508837869000,
      'moduser': null,
      'acctid': null,
      'edmmArithmeticDesc': 'http://localhost:11101/orde/save',
      'edmmArithmeticStorage': '',
      'edmmArithmeticSourceName': '',
      'edmmRequestType': '1',
      'edmmMethodType': '0',
      'edmmExecRate': '0',
      'edmmStartTime': '00:00',
      'edmmEndTime': '12:00',
      'edmmTypeName': '单据类方法',
      'edmtName': null,
      'edmProgramTypeName': null,
      'edmEdmdStatusName': null,
      'edmcName': '监管设置单类',
      'edmcId': null,
      'edmEdmdInsertArgType': null,
      'edmEdmdInsertArgName': null,
      'edmInsertArgDesc': null,
      'edmEdmdReturnArgType': null,
      'edmEdmdReturnName': null,
      'edmReturnDesc': null,
      'addtimeStr': '2017-10-24 17:37:25',
      'modtimeStr': '2017-10-24 17:37:49',
      'edmdVersion': null,
      'edmdId': null,
      'edmdStatus': null,
      'edcmId': '57e5a91e4b4c41399d8fe429143866bd',
      'edmmProgramSourceName': '',
      'edmTriggerCondName': null,
      'edmTriggerCondNameDesc': null,
      'disabled': true,
      'controlId': '7bcf6fe9-230d-4f98-a6da-6354b3be5ee4'
    }, {
      'id': '5730bfbfef744ba0ac9df8a5db386cb6',
      'edmmType': 'a3c01a6383ce4bb79c4d603b96c71831',
      'isCover': 0,
      'edmmName': 'orde_create',
      'edmmDesc': '创建一个”单据类对象”草稿, 该方法由”单据定义类对象”调用',
      'edmmProgramType': '1',
      'edmmProgramStorage': null,
      'edmmTriggerCond': '',
      'edmmVer': '',
      'edmmDevelopDept': '',
      'edmmProgrammer': '',
      'edmmSeq': 2,
      'edmmStatus': '1',
      'edmmUpdateDesc': '',
      'isPlatformProgram': 0,
      'isDefined': null,
      'isDel': 0,
      'addtime': 1508837422000,
      'adduser': null,
      'modtime': 1508838926000,
      'moduser': null,
      'acctid': null,
      'edmmArithmeticDesc': 'http://form-client-driver/orde/create',
      'edmmArithmeticStorage': '',
      'edmmArithmeticSourceName': '',
      'edmmRequestType': '1',
      'edmmMethodType': '0',
      'edmmExecRate': '0',
      'edmmStartTime': '00:00',
      'edmmEndTime': '12:00',
      'edmmTypeName': '单据类方法',
      'edmtName': null,
      'edmProgramTypeName': null,
      'edmEdmdStatusName': null,
      'edmcName': '监管设置单类',
      'edmcId': null,
      'edmEdmdInsertArgType': null,
      'edmEdmdInsertArgName': null,
      'edmInsertArgDesc': null,
      'edmEdmdReturnArgType': null,
      'edmEdmdReturnName': null,
      'edmReturnDesc': null,
      'addtimeStr': '2017-10-24 17:30:22',
      'modtimeStr': '2017-10-24 17:55:26',
      'edmdVersion': null,
      'edmdId': null,
      'edmdStatus': null,
      'edcmId': 'cfa24e09ad6e4c95953c7386a2075ef0',
      'edmmProgramSourceName': '',
      'edmTriggerCondName': null,
      'edmTriggerCondNameDesc': null,
      'disabled': true,
      'controlId': 'b1a95fd3-7019-467c-8dbe-258bc56d17b4'
    }],
    'methodDBModel': 'orde_save',
    'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {'name': '百分比', 'default': '50', 'value': 'percentLayout', 'status': true, 'max': 100}, {
      'name': '像素',
      'default': '',
      'value': 'pixelLayout',
      'status': false,
      'max': null
    }, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
    'CAttribute': {
      'type': [{'value': 'primary', 'name': '提交', 'default': 'primary'}, {'value': 'danger', 'name': '审批', 'default': 'danger'}, {
        'value': '',
        'name': '普通',
        'default': ''
      }, {'value': 'info', 'name': '详情', 'default': 'info'}],
      'typeModel': 'primary',
      'size': [{'value': 'large', 'name': '大'}, {'value': '', 'name': '普通'}, {'value': 'small', 'name': '小'}, {'value': 'mini', 'name': '微型'}],
      'sizeModel': '',
      'description': '',
      'height': '',
      'vertical': ['top', 'middle', 'bottom']
    },
    'CKey': {'default': 'orde_save', 'type': '', 'keyMethods': ''},
    'Status': {'status': false, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': []},
    'Icon': {
      'status': false,
      'chooseStatus': false,
      'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
      'positionModel': '',
      'className': '',
      'content': '',
      'title': '',
      'library': ''
    },
    'ControlProperties': ''
  },
  'id': '7bcf6fe9-230d-4f98-a6da-6354b3be5ee4'
}, {
  'CNameCN': '布局控件',
  'CNameEN': 'layout',
  'parent': 'form',
  'type': 'layout',
  'component': 'CLayout',
  'config': {
    'ControlID': '2413be84-a913-4950-8b43-38a446e1d876',
    'CBelong': 'form',
    'CTitleCN': '布局控件',
    'CTitleEN': 'layout Control',
    'CName': 'CLayout',
    'layoutModel': 'percentLayout',
    'currentLayout': {'name': '百分比布局', 'default': 100, 'value': 'percentLayout', 'status': true, 'max': 100},
    'CLayout': [{'name': '自适应布局', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {
      'name': '百分比布局',
      'default': 100,
      'value': 'percentLayout',
      'status': true,
      'max': 100
    }, {'name': '像素布局', 'default': 100, 'value': 'pixelLayout', 'status': false, 'max': null}, {'name': '栅格布局', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
    'CAttribute': {'description': '', 'height': '', 'vertical': ['top', 'middle', 'bottom']},
    'CKey': {'default': '', 'type': '', 'keyMethods': ''},
    'CValidate': {'status': false, 'chooseStatus': false, 'validateModel': ''},
    'ControlProperties': '',
    'methodDBModel': ''
  },
  'children': [[{
    'CNameCN': '输入框',
    'CNameEN': 'input',
    'parent': 'form',
    'type': 'input',
    'component': 'CInput',
    'config': {
      'ControlProperties': 'mtor_cls_id',
      'ControlID': '024a0d34-f2ac-40c9-9b3b-1995d214972e',
      'CBelong': 'form',
      'CTitleCN': '监管树类',
      'CTitleEN': 'input Control',
      'CName': 'CInput',
      'labelPositionModel': 'right',
      'labelPositionValue': [{'value': 'left', 'name': '左对齐'}, {'value': 'right', 'name': '右对齐'}, {'value': 'top', 'name': '居上对齐'}],
      'labelWidth': 80,
      'layoutModel': 'percentLayout',
      'currentLayout': {'name': '百分比', 'default': 100, 'value': 'percentLayout', 'status': true, 'max': 100},
      'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {
        'name': '百分比',
        'default': 100,
        'value': 'percentLayout',
        'status': true,
        'max': 100
      }, {'name': '像素', 'default': 100, 'value': 'pixelLayout', 'status': false, 'max': null}, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
      'CAttribute': {
        'prepend': 'Tree',
        'append': '监管树',
        'type': [{'value': 'input', 'name': '文本框'}, {'value': 'textarea', 'name': '多行文本'}],
        'typeModel': 'input',
        'description': '',
        'placeholder': '请输入监管树类',
        'height': '',
        'vertical': ['top', 'middle', 'bottom']
      },
      'CKey': {'default': '', 'type': '', 'keyMethods': ''},
      'Status': {'status': false, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': []},
      'Icon': {
        'status': false,
        'chooseStatus': false,
        'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
        'positionModel': '',
        'className': '',
        'content': '',
        'title': '',
        'library': ''
      },
      'CValidate': {'status': false, 'chooseStatus': false, 'validateModel': ''},
      'methodDB': [{'name': '提交', 'methodName': 'save', 'action': '/form/saveAction'}],
      'methodDBModel': ''
    },
    'id': '8d640a4c-2ded-48ca-86e2-694710453210'
  }, {
    'CNameCN': '输入框',
    'CNameEN': 'input',
    'parent': 'form',
    'type': 'input',
    'component': 'CInput',
    'config': {
      'ControlProperties': 'mtor_order_type',
      'ControlID': '024a0d34-f2ac-40c9-9b3b-1995d214972e',
      'CBelong': 'form',
      'CTitleCN': '变更类型',
      'CTitleEN': 'input Control',
      'CName': 'CInput',
      'labelPositionModel': 'right',
      'labelPositionValue': [{'value': 'left', 'name': '左对齐'}, {'value': 'right', 'name': '右对齐'}, {'value': 'top', 'name': '居上对齐'}],
      'labelWidth': 80,
      'layoutModel': 'percentLayout',
      'currentLayout': {'name': '百分比', 'default': 100, 'value': 'percentLayout', 'status': true, 'max': 100},
      'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {
        'name': '百分比',
        'default': 100,
        'value': 'percentLayout',
        'status': true,
        'max': 100
      }, {'name': '像素', 'default': 100, 'value': 'pixelLayout', 'status': false, 'max': null}, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
      'CAttribute': {
        'prepend': 'Type',
        'append': '变更类型',
        'type': [{'value': 'input', 'name': '文本框'}, {'value': 'textarea', 'name': '多行文本'}],
        'typeModel': 'input',
        'description': '',
        'placeholder': '请输入变更类型',
        'height': '',
        'vertical': ['top', 'middle', 'bottom']
      },
      'CKey': {'default': '', 'type': '', 'keyMethods': ''},
      'Status': {'status': false, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': []},
      'Icon': {
        'status': false,
        'chooseStatus': false,
        'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
        'positionModel': '',
        'className': '',
        'content': '',
        'title': '',
        'library': ''
      },
      'CValidate': {'status': false, 'chooseStatus': false, 'validateModel': ''},
      'methodDB': [{'name': '提交', 'methodName': 'save', 'action': '/form/saveAction'}],
      'methodDBModel': ''
    },
    'id': '826fd208-145a-457f-9d88-3c46ae60ecf8'
  }, {
    'CNameCN': '输入框',
    'CNameEN': 'input',
    'parent': 'form',
    'type': 'input',
    'component': 'CInput',
    'config': {
      'ControlProperties': 'mtor_order_root',
      'ControlID': '024a0d34-f2ac-40c9-9b3b-1995d214972e',
      'CBelong': 'form',
      'CTitleCN': '对象节点',
      'CTitleEN': 'input Control',
      'CName': 'CInput',
      'labelPositionModel': 'right',
      'labelPositionValue': [{'value': 'left', 'name': '左对齐'}, {'value': 'right', 'name': '右对齐'}, {'value': 'top', 'name': '居上对齐'}],
      'labelWidth': 80,
      'layoutModel': 'percentLayout',
      'currentLayout': {'name': '百分比', 'default': 100, 'value': 'percentLayout', 'status': true, 'max': 100},
      'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {
        'name': '百分比',
        'default': 100,
        'value': 'percentLayout',
        'status': true,
        'max': 100
      }, {'name': '像素', 'default': 100, 'value': 'pixelLayout', 'status': false, 'max': null}, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
      'CAttribute': {
        'prepend': 'Node',
        'append': '节点',
        'type': [{'value': 'input', 'name': '文本框'}, {'value': 'textarea', 'name': '多行文本'}],
        'typeModel': 'input',
        'description': '',
        'placeholder': '请输入节点对象',
        'height': '',
        'vertical': ['top', 'middle', 'bottom']
      },
      'CKey': {'default': '', 'type': '', 'keyMethods': ''},
      'Status': {'status': false, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': []},
      'Icon': {
        'status': false,
        'chooseStatus': false,
        'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
        'positionModel': '',
        'className': '',
        'content': '',
        'title': '',
        'library': ''
      },
      'CValidate': {'status': false, 'chooseStatus': false, 'validateModel': ''},
      'methodDB': [{'name': '提交', 'methodName': 'save', 'action': '/form/saveAction'}],
      'methodDBModel': ''
    },
    'id': 'b8cdb67f-bdd1-4fd9-b660-c9fa54d6231d'
  }, {
    'CNameCN': '输入框',
    'CNameEN': 'input',
    'parent': 'form',
    'type': 'input',
    'component': 'CInput',
    'config': {
      'ControlProperties': 'mtor_node_set',
      'ControlID': '024a0d34-f2ac-40c9-9b3b-1995d214972e',
      'CBelong': 'form',
      'CTitleCN': '节点集合',
      'CTitleEN': 'input Control',
      'CName': 'CInput',
      'labelPositionModel': 'right',
      'labelPositionValue': [{'value': 'left', 'name': '左对齐'}, {'value': 'right', 'name': '右对齐'}, {'value': 'top', 'name': '居上对齐'}],
      'labelWidth': 80,
      'layoutModel': 'percentLayout',
      'currentLayout': {'name': '百分比', 'default': 100, 'value': 'percentLayout', 'status': true, 'max': 100},
      'CLayout': [{'name': '自适应', 'default': 1, 'value': 'flexLayout', 'status': false, 'max': 10}, {
        'name': '百分比',
        'default': 100,
        'value': 'percentLayout',
        'status': true,
        'max': 100
      }, {'name': '像素', 'default': 100, 'value': 'pixelLayout', 'status': false, 'max': null}, {'name': '栅格', 'default': 12, 'value': 'columnLayout', 'status': false, 'max': 12}],
      'CAttribute': {
        'prepend': 'Array',
        'append': '节点集合',
        'type': [{'value': 'input', 'name': '文本框'}, {'value': 'textarea', 'name': '多行文本'}],
        'typeModel': 'input',
        'description': '',
        'placeholder': '请输入节点集合',
        'height': '',
        'vertical': ['top', 'middle', 'bottom']
      },
      'CKey': {'default': '', 'type': '', 'keyMethods': ''},
      'Status': {'status': true, 'rules': [{'value': 'readonly', 'name': '只读'}, {'value': '', 'name': '隐藏'}], 'ruleList': ['readonly']},
      'Icon': {
        'status': false,
        'chooseStatus': false,
        'position': [{'name': '左侧', 'value': 'left'}, {'name': '右侧', 'value': 'right'}],
        'positionModel': '',
        'className': '',
        'content': '',
        'title': '',
        'library': ''
      },
      'CValidate': {'status': false, 'chooseStatus': false, 'validateModel': ''},
      'methodDB': [{'name': '提交', 'methodName': 'save', 'action': '/form/saveAction'}],
      'methodDBModel': ''
    },
    'id': 'df633dbd-c80e-4b71-85ec-99802ae1c827'
  }]],
  'childrenDefault': [[]],
  'id': '2413be84-a913-4950-8b43-38a446e1d876'
}]

export default FormData

